package com.theo.models;
// Generated 18/02/2017 10:43:58 PM by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int id;
     private Distrito distrito;
     private String nombres;
     private String apellidos;
     private int edad;
     private String dni;
     private String direccion;

    public Persona() {
    }

	
    public Persona(int id, String nombres, String apellidos, int edad, String dni) {
        this.id = id;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.edad = edad;
        this.dni = dni;
    }
    public Persona(int id, Distrito distrito, String nombres, String apellidos, int edad, String dni, String direccion) {
       this.id = id;
       this.distrito = distrito;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.edad = edad;
       this.dni = dni;
       this.direccion = direccion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Distrito getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(Distrito distrito) {
        this.distrito = distrito;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


