package com.theo.models;
// Generated 18/02/2017 10:43:58 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int usuIde;
     private String username;
     private String password;

    public Usuario() {
    }

	
    public Usuario(int usuIde) {
        this.usuIde = usuIde;
    }
    public Usuario(int usuIde, String username, String password) {
       this.usuIde = usuIde;
       this.username = username;
       this.password = password;
    }
   
    public int getUsuIde() {
        return this.usuIde;
    }
    
    public void setUsuIde(int usuIde) {
        this.usuIde = usuIde;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


